services:
  jinji_back:
    build: ./jinji_back
    ports:
      - "8080:8080"
    environment:
      - NEON_CONNECT=${NEON_CONNECT}
  jinji_front:
    build: ./jinji_front
    ports:
      - "3000:3000"
